version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network_healthcare_system

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - network_healthcare_system

  healthcare_app:
    build:
      context: ../../healthcare_app
      dockerfile: docker/Dockerfile.api
      args:
        - SECRET_KEY=kIZYwkJQUnZG4YufGkIOSRZ83J5lbQO+ahfuq38xlqs=
        - POSTGRES_URL=postgresql://user:user@db:5432/healthcare_db
        - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    restart: always
    expose:
      - "8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - network_healthcare_system

  celery_beat:
    build:
      context: ../../healthcare_app/
      dockerfile: docker/Dockerfile.celery_beat
      args:
        - SECRET_KEY=test_key
        - POSTGRES_URL=postgresql://user:user@db:5432/healthcare_db
        - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    restart: always
    depends_on:
      - healthcare_app
      - db
      - rabbitmq
    networks:
      - network_healthcare_system

  celery_worker:
    build:
      context: ../../healthcare_app/
      dockerfile: docker/Dockerfile.celery_worker
      args:
        - SECRET_KEY=test_key
        - POSTGRES_URL=postgresql://user:user@db:5432/healthcare_db
        - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    restart: always
    depends_on:
      - healthcare_app
      - db
      - rabbitmq
    networks:
      - network_healthcare_system

  healthcare_analytics:
    build:
      context: ../../healthcare_analytics/
      args:
        - SECRET_KEY=kIZYwkJQUnZG4YufGkIOSRZ83J5lbQO+ahfuq38xlqs=
        - POSTGRES_URL=postgresql+asyncpg://user:user@db:5432/healthcare_db
    restart: always
    expose:
      - "10000"
    depends_on:
      - healthcare_app
      - db
    networks:
      - network_healthcare_system

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - healthcare_app
      - healthcare_analytics
    networks:
      - network_healthcare_system

networks:
  network_healthcare_system:
    driver: bridge

volumes:
  db_data: